### ISSUE TITLE
 bitcoin-sv2-tp-0.1.2-arm64-apple-darwin doesn't open on macos

### ISSUE THREAD

**Issue by bernardoaraujor** [Sjors/bitcoin#40]
![image](https://github.com/Sjors/bitcoin/assets/9698228/fc4c7a54-da2c-41e2-8fd3-00ce41d2fcfb)

**Comment by plebhash** [comment]
apparently this is a fix: https://bitcoin.stackexchange.com/questions/117098/bitcoind-wont-run-on-macos/117961#117961

**Comment by Sjors** [comment]
@bernardoaraujor do you have an intel mac or the newer M1/M2/M3? Which version of macOS?

**Comment by bernardoaraujor** [comment]
M2 max, Sonoma 14.4.1

**Comment by Sjors** [comment]
Did the self-signing workaround from @plebhash work? I can't sign these binaries unfortunately.

**Comment by Sjors** [comment]
Feel free to reopen if you have more info.
