### ISSUE TITLE
`testnet4` support on `sv2` branch

### ISSUE THREAD

**Issue by plebhash** [Sjors/bitcoin#41]
### Please describe the feature you'd like to see added.

please make `sv2` branch support `testnet4`

https://github.com/bitcoin/bitcoin/pull/29775

### Is your feature related to a problem, if so please describe it.

Lopp's blockstorm is making SV2 testing on `testnet3` useless and unrealistic.

**Comment by Sjors** [comment]
For now I suggest cherry-picking the testnet4 commits on top of the sv2 branch. Once testnet4 is merged, I'll rebase.

**Comment by plebhash** [comment]
ping @gitgab19

we no longer need to update VPS with @stratospher fork, just pull @Sjors `sv2` branch and re-build
