### ISSUE TITLE
Impossible to kill `bitcoind`

### ISSUE THREAD

**Issue by plebhash** [Sjors/bitcoin#43]
Bringing over this [Conversation from Discord](https://discordapp.com/channels/950687892169195530/1179824984592490496/1246781000743125034) so it doesn't get lost:

@Fi3:
> the hosted (SRI vps) bitcoin node always goes in a state where it is impossible to kill it with ctrl-c. This never happen on the node that I run locally or the ones that I run for demand. @Sjors @gitgab19 
> Not sure if this is an issue or not, but I wanted to log it

@GitGab19
> Can you make sure it's running the latest commit? I never noticed this behaviour

@Fi3
> I didn't touch it
> just restart it sometimes

**Comment by Sjors** [comment]
I think I've seen this occasionally. There's probably some thread locking order problem in the Template Provider.

**Comment by Sjors** [comment]
I think I've ironed out these issues. Please try the latest release: https://github.com/Sjors/bitcoin/releases/tag/sv2-tp-0.1.4

**Comment by Sjors** [comment]
Much has been refactored since, please open a new issue if it still happens though.
